"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AppState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AppStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AppState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APP_CLOSED: _AppState.ValueType
    APP_STARTED: _AppState.ValueType

class AppState(_AppState, metaclass=_AppStateEnumTypeWrapper):
    ...
APP_CLOSED: AppState.ValueType
APP_STARTED: AppState.ValueType
Global___AppState: typing_extensions.TypeAlias = AppState

@typing.final
class StartRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    name: builtins.str
    args: builtins.str

    def __init__(self, *, name: builtins.str=..., args: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['args', b'args', 'name', b'name']) -> None:
        ...
Global___StartRequest: typing_extensions.TypeAlias = StartRequest

@typing.final
class LockStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___LockStatusRequest: typing_extensions.TypeAlias = LockStatusRequest

@typing.final
class LockStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOCKED_FIELD_NUMBER: builtins.int
    locked: builtins.bool

    def __init__(self, *, locked: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['locked', b'locked']) -> None:
        ...
Global___LockStatusResponse: typing_extensions.TypeAlias = LockStatusResponse

@typing.final
class AppExitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___AppExitRequest: typing_extensions.TypeAlias = AppExitRequest

@typing.final
class AppLoadFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___AppLoadFileRequest: typing_extensions.TypeAlias = AppLoadFileRequest

@typing.final
class AppButtonPressRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARGS_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    args: builtins.str
    index: builtins.int

    def __init__(self, *, args: builtins.str=..., index: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['args', b'args', 'index', b'index']) -> None:
        ...
Global___AppButtonPressRequest: typing_extensions.TypeAlias = AppButtonPressRequest

@typing.final
class AppButtonReleaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___AppButtonReleaseRequest: typing_extensions.TypeAlias = AppButtonReleaseRequest

@typing.final
class AppButtonPressReleaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARGS_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    args: builtins.str
    index: builtins.int

    def __init__(self, *, args: builtins.str=..., index: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['args', b'args', 'index', b'index']) -> None:
        ...
Global___AppButtonPressReleaseRequest: typing_extensions.TypeAlias = AppButtonPressReleaseRequest

@typing.final
class AppStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    state: Global___AppState.ValueType

    def __init__(self, *, state: Global___AppState.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['state', b'state']) -> None:
        ...
Global___AppStateResponse: typing_extensions.TypeAlias = AppStateResponse

@typing.final
class GetErrorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___GetErrorRequest: typing_extensions.TypeAlias = GetErrorRequest

@typing.final
class GetErrorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    code: builtins.int
    text: builtins.str

    def __init__(self, *, code: builtins.int=..., text: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['code', b'code', 'text', b'text']) -> None:
        ...
Global___GetErrorResponse: typing_extensions.TypeAlias = GetErrorResponse

@typing.final
class DataExchangeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data', b'data']) -> None:
        ...
Global___DataExchangeRequest: typing_extensions.TypeAlias = DataExchangeRequest