"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IsLockedRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___IsLockedRequest: typing_extensions.TypeAlias = IsLockedRequest

@typing.final
class UnlockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___UnlockRequest: typing_extensions.TypeAlias = UnlockRequest

@typing.final
class StatusSubscribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StatusSubscribeRequest: typing_extensions.TypeAlias = StatusSubscribeRequest

@typing.final
class StatusUnsubscribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StatusUnsubscribeRequest: typing_extensions.TypeAlias = StatusUnsubscribeRequest

@typing.final
class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOCKED_FIELD_NUMBER: builtins.int
    locked: builtins.bool

    def __init__(self, *, locked: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['locked', b'locked']) -> None:
        ...
Global___Status: typing_extensions.TypeAlias = Status