"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str

    def __init__(self, *, key: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key']) -> None:
        ...
Global___GetRequest: typing_extensions.TypeAlias = GetRequest

@typing.final
class GetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str

    def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
        ...
Global___GetResponse: typing_extensions.TypeAlias = GetResponse