"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data', b'data']) -> None:
        ...
Global___PingRequest: typing_extensions.TypeAlias = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes

    def __init__(self, *, data: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data', b'data']) -> None:
        ...
Global___PingResponse: typing_extensions.TypeAlias = PingResponse

@typing.final
class RebootRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RebootMode:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RebootModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RebootRequest._RebootMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OS: RebootRequest._RebootMode.ValueType
        'default value'
        DFU: RebootRequest._RebootMode.ValueType
        UPDATE: RebootRequest._RebootMode.ValueType

    class RebootMode(_RebootMode, metaclass=_RebootModeEnumTypeWrapper):
        ...
    OS: RebootRequest.RebootMode.ValueType
    'default value'
    DFU: RebootRequest.RebootMode.ValueType
    UPDATE: RebootRequest.RebootMode.ValueType
    MODE_FIELD_NUMBER: builtins.int
    mode: Global___RebootRequest.RebootMode.ValueType

    def __init__(self, *, mode: Global___RebootRequest.RebootMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mode', b'mode']) -> None:
        ...
Global___RebootRequest: typing_extensions.TypeAlias = RebootRequest

@typing.final
class DeviceInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___DeviceInfoRequest: typing_extensions.TypeAlias = DeviceInfoRequest

@typing.final
class DeviceInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str

    def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
        ...
Global___DeviceInfoResponse: typing_extensions.TypeAlias = DeviceInfoResponse

@typing.final
class FactoryResetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___FactoryResetRequest: typing_extensions.TypeAlias = FactoryResetRequest

@typing.final
class GetDateTimeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___GetDateTimeRequest: typing_extensions.TypeAlias = GetDateTimeRequest

@typing.final
class GetDateTimeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATETIME_FIELD_NUMBER: builtins.int

    @property
    def datetime(self) -> Global___DateTime:
        ...

    def __init__(self, *, datetime: Global___DateTime | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['datetime', b'datetime']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['datetime', b'datetime']) -> None:
        ...
Global___GetDateTimeResponse: typing_extensions.TypeAlias = GetDateTimeResponse

@typing.final
class SetDateTimeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATETIME_FIELD_NUMBER: builtins.int

    @property
    def datetime(self) -> Global___DateTime:
        ...

    def __init__(self, *, datetime: Global___DateTime | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['datetime', b'datetime']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['datetime', b'datetime']) -> None:
        ...
Global___SetDateTimeRequest: typing_extensions.TypeAlias = SetDateTimeRequest

@typing.final
class DateTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HOUR_FIELD_NUMBER: builtins.int
    MINUTE_FIELD_NUMBER: builtins.int
    SECOND_FIELD_NUMBER: builtins.int
    DAY_FIELD_NUMBER: builtins.int
    MONTH_FIELD_NUMBER: builtins.int
    YEAR_FIELD_NUMBER: builtins.int
    WEEKDAY_FIELD_NUMBER: builtins.int
    hour: builtins.int
    'Time\n    *< Hour in 24H format: 0-23\n    '
    minute: builtins.int
    '*< Minute: 0-59'
    second: builtins.int
    '*< Second: 0-59'
    day: builtins.int
    'Date\n    *< Current day: 1-31\n    '
    month: builtins.int
    '*< Current month: 1-12'
    year: builtins.int
    '*< Current year: 2000-2099'
    weekday: builtins.int
    '*< Current weekday: 1-7'

    def __init__(self, *, hour: builtins.int=..., minute: builtins.int=..., second: builtins.int=..., day: builtins.int=..., month: builtins.int=..., year: builtins.int=..., weekday: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['day', b'day', 'hour', b'hour', 'minute', b'minute', 'month', b'month', 'second', b'second', 'weekday', b'weekday', 'year', b'year']) -> None:
        ...
Global___DateTime: typing_extensions.TypeAlias = DateTime

@typing.final
class PlayAudiovisualAlertRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___PlayAudiovisualAlertRequest: typing_extensions.TypeAlias = PlayAudiovisualAlertRequest

@typing.final
class ProtobufVersionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ProtobufVersionRequest: typing_extensions.TypeAlias = ProtobufVersionRequest

@typing.final
class ProtobufVersionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAJOR_FIELD_NUMBER: builtins.int
    MINOR_FIELD_NUMBER: builtins.int
    major: builtins.int
    minor: builtins.int

    def __init__(self, *, major: builtins.int=..., minor: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['major', b'major', 'minor', b'minor']) -> None:
        ...
Global___ProtobufVersionResponse: typing_extensions.TypeAlias = ProtobufVersionResponse

@typing.final
class UpdateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UPDATE_MANIFEST_FIELD_NUMBER: builtins.int
    update_manifest: builtins.str

    def __init__(self, *, update_manifest: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['update_manifest', b'update_manifest']) -> None:
        ...
Global___UpdateRequest: typing_extensions.TypeAlias = UpdateRequest

@typing.final
class UpdateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _UpdateResultCode:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UpdateResultCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateResponse._UpdateResultCode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        OK: UpdateResponse._UpdateResultCode.ValueType
        ManifestPathInvalid: UpdateResponse._UpdateResultCode.ValueType
        ManifestFolderNotFound: UpdateResponse._UpdateResultCode.ValueType
        ManifestInvalid: UpdateResponse._UpdateResultCode.ValueType
        StageMissing: UpdateResponse._UpdateResultCode.ValueType
        StageIntegrityError: UpdateResponse._UpdateResultCode.ValueType
        ManifestPointerError: UpdateResponse._UpdateResultCode.ValueType
        TargetMismatch: UpdateResponse._UpdateResultCode.ValueType
        OutdatedManifestVersion: UpdateResponse._UpdateResultCode.ValueType
        IntFull: UpdateResponse._UpdateResultCode.ValueType
        UnspecifiedError: UpdateResponse._UpdateResultCode.ValueType

    class UpdateResultCode(_UpdateResultCode, metaclass=_UpdateResultCodeEnumTypeWrapper):
        ...
    OK: UpdateResponse.UpdateResultCode.ValueType
    ManifestPathInvalid: UpdateResponse.UpdateResultCode.ValueType
    ManifestFolderNotFound: UpdateResponse.UpdateResultCode.ValueType
    ManifestInvalid: UpdateResponse.UpdateResultCode.ValueType
    StageMissing: UpdateResponse.UpdateResultCode.ValueType
    StageIntegrityError: UpdateResponse.UpdateResultCode.ValueType
    ManifestPointerError: UpdateResponse.UpdateResultCode.ValueType
    TargetMismatch: UpdateResponse.UpdateResultCode.ValueType
    OutdatedManifestVersion: UpdateResponse.UpdateResultCode.ValueType
    IntFull: UpdateResponse.UpdateResultCode.ValueType
    UnspecifiedError: UpdateResponse.UpdateResultCode.ValueType
    CODE_FIELD_NUMBER: builtins.int
    code: Global___UpdateResponse.UpdateResultCode.ValueType

    def __init__(self, *, code: Global___UpdateResponse.UpdateResultCode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['code', b'code']) -> None:
        ...
Global___UpdateResponse: typing_extensions.TypeAlias = UpdateResponse

@typing.final
class PowerInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___PowerInfoRequest: typing_extensions.TypeAlias = PowerInfoRequest

@typing.final
class PowerInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str

    def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
        ...
Global___PowerInfoResponse: typing_extensions.TypeAlias = PowerInfoResponse