"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _GpioPin:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioPinEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioPin.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PC0: _GpioPin.ValueType
    PC1: _GpioPin.ValueType
    PC3: _GpioPin.ValueType
    PB2: _GpioPin.ValueType
    PB3: _GpioPin.ValueType
    PA4: _GpioPin.ValueType
    PA6: _GpioPin.ValueType
    PA7: _GpioPin.ValueType

class GpioPin(_GpioPin, metaclass=_GpioPinEnumTypeWrapper):
    ...
PC0: GpioPin.ValueType
PC1: GpioPin.ValueType
PC3: GpioPin.ValueType
PB2: GpioPin.ValueType
PB3: GpioPin.ValueType
PA4: GpioPin.ValueType
PA6: GpioPin.ValueType
PA7: GpioPin.ValueType
Global___GpioPin: typing_extensions.TypeAlias = GpioPin

class _GpioPinMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioPinModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioPinMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OUTPUT: _GpioPinMode.ValueType
    INPUT: _GpioPinMode.ValueType

class GpioPinMode(_GpioPinMode, metaclass=_GpioPinModeEnumTypeWrapper):
    ...
OUTPUT: GpioPinMode.ValueType
INPUT: GpioPinMode.ValueType
Global___GpioPinMode: typing_extensions.TypeAlias = GpioPinMode

class _GpioInputPull:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioInputPullEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioInputPull.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NO: _GpioInputPull.ValueType
    UP: _GpioInputPull.ValueType
    DOWN: _GpioInputPull.ValueType

class GpioInputPull(_GpioInputPull, metaclass=_GpioInputPullEnumTypeWrapper):
    ...
NO: GpioInputPull.ValueType
UP: GpioInputPull.ValueType
DOWN: GpioInputPull.ValueType
Global___GpioInputPull: typing_extensions.TypeAlias = GpioInputPull

class _GpioOtgMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GpioOtgModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GpioOtgMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OFF: _GpioOtgMode.ValueType
    ON: _GpioOtgMode.ValueType

class GpioOtgMode(_GpioOtgMode, metaclass=_GpioOtgModeEnumTypeWrapper):
    ...
OFF: GpioOtgMode.ValueType
ON: GpioOtgMode.ValueType
Global___GpioOtgMode: typing_extensions.TypeAlias = GpioOtgMode

@typing.final
class SetPinMode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIN_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    pin: Global___GpioPin.ValueType
    mode: Global___GpioPinMode.ValueType

    def __init__(self, *, pin: Global___GpioPin.ValueType=..., mode: Global___GpioPinMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mode', b'mode', 'pin', b'pin']) -> None:
        ...
Global___SetPinMode: typing_extensions.TypeAlias = SetPinMode

@typing.final
class SetInputPull(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIN_FIELD_NUMBER: builtins.int
    PULL_MODE_FIELD_NUMBER: builtins.int
    pin: Global___GpioPin.ValueType
    pull_mode: Global___GpioInputPull.ValueType

    def __init__(self, *, pin: Global___GpioPin.ValueType=..., pull_mode: Global___GpioInputPull.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['pin', b'pin', 'pull_mode', b'pull_mode']) -> None:
        ...
Global___SetInputPull: typing_extensions.TypeAlias = SetInputPull

@typing.final
class GetPinMode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIN_FIELD_NUMBER: builtins.int
    pin: Global___GpioPin.ValueType

    def __init__(self, *, pin: Global___GpioPin.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['pin', b'pin']) -> None:
        ...
Global___GetPinMode: typing_extensions.TypeAlias = GetPinMode

@typing.final
class GetPinModeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODE_FIELD_NUMBER: builtins.int
    mode: Global___GpioPinMode.ValueType

    def __init__(self, *, mode: Global___GpioPinMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mode', b'mode']) -> None:
        ...
Global___GetPinModeResponse: typing_extensions.TypeAlias = GetPinModeResponse

@typing.final
class ReadPin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIN_FIELD_NUMBER: builtins.int
    pin: Global___GpioPin.ValueType

    def __init__(self, *, pin: Global___GpioPin.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['pin', b'pin']) -> None:
        ...
Global___ReadPin: typing_extensions.TypeAlias = ReadPin

@typing.final
class ReadPinResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.int

    def __init__(self, *, value: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['value', b'value']) -> None:
        ...
Global___ReadPinResponse: typing_extensions.TypeAlias = ReadPinResponse

@typing.final
class WritePin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PIN_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    pin: Global___GpioPin.ValueType
    value: builtins.int

    def __init__(self, *, pin: Global___GpioPin.ValueType=..., value: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['pin', b'pin', 'value', b'value']) -> None:
        ...
Global___WritePin: typing_extensions.TypeAlias = WritePin

@typing.final
class GetOtgMode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___GetOtgMode: typing_extensions.TypeAlias = GetOtgMode

@typing.final
class GetOtgModeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODE_FIELD_NUMBER: builtins.int
    mode: Global___GpioOtgMode.ValueType

    def __init__(self, *, mode: Global___GpioOtgMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mode', b'mode']) -> None:
        ...
Global___GetOtgModeResponse: typing_extensions.TypeAlias = GetOtgModeResponse

@typing.final
class SetOtgMode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODE_FIELD_NUMBER: builtins.int
    mode: Global___GpioOtgMode.ValueType

    def __init__(self, *, mode: Global___GpioOtgMode.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mode', b'mode']) -> None:
        ...
Global___SetOtgMode: typing_extensions.TypeAlias = SetOtgMode