"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InputKey:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputKeyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputKey.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UP: _InputKey.ValueType
    DOWN: _InputKey.ValueType
    RIGHT: _InputKey.ValueType
    LEFT: _InputKey.ValueType
    OK: _InputKey.ValueType
    BACK: _InputKey.ValueType

class InputKey(_InputKey, metaclass=_InputKeyEnumTypeWrapper):
    ...
UP: InputKey.ValueType
DOWN: InputKey.ValueType
RIGHT: InputKey.ValueType
LEFT: InputKey.ValueType
OK: InputKey.ValueType
BACK: InputKey.ValueType
Global___InputKey: typing_extensions.TypeAlias = InputKey

class _InputType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRESS: _InputType.ValueType
    '*< Press event, emitted after de-bounce'
    RELEASE: _InputType.ValueType
    '*< Release event, emitted after de-bounce'
    SHORT: _InputType.ValueType
    '*< Short event, emitted after InputTypeRelease done withing INPUT_LONG_PRESS interval'
    LONG: _InputType.ValueType
    '*< Long event, emitted after INPUT_LONG_PRESS interval, asynchronous to InputTypeRelease'
    REPEAT: _InputType.ValueType
    '*< Repeat event, emitted with INPUT_REPEATE_PRESS period after InputTypeLong event'

class InputType(_InputType, metaclass=_InputTypeEnumTypeWrapper):
    ...
PRESS: InputType.ValueType
'*< Press event, emitted after de-bounce'
RELEASE: InputType.ValueType
'*< Release event, emitted after de-bounce'
SHORT: InputType.ValueType
'*< Short event, emitted after InputTypeRelease done withing INPUT_LONG_PRESS interval'
LONG: InputType.ValueType
'*< Long event, emitted after INPUT_LONG_PRESS interval, asynchronous to InputTypeRelease'
REPEAT: InputType.ValueType
'*< Repeat event, emitted with INPUT_REPEATE_PRESS period after InputTypeLong event'
Global___InputType: typing_extensions.TypeAlias = InputType

class _ScreenOrientation:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ScreenOrientationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ScreenOrientation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HORIZONTAL: _ScreenOrientation.ValueType
    '*< Horizontal'
    HORIZONTAL_FLIP: _ScreenOrientation.ValueType
    '*< Horizontal flipped (180)'
    VERTICAL: _ScreenOrientation.ValueType
    '*< Vertical (90)'
    VERTICAL_FLIP: _ScreenOrientation.ValueType
    '*< Vertical flipped (270)'

class ScreenOrientation(_ScreenOrientation, metaclass=_ScreenOrientationEnumTypeWrapper):
    ...
HORIZONTAL: ScreenOrientation.ValueType
'*< Horizontal'
HORIZONTAL_FLIP: ScreenOrientation.ValueType
'*< Horizontal flipped (180)'
VERTICAL: ScreenOrientation.ValueType
'*< Vertical (90)'
VERTICAL_FLIP: ScreenOrientation.ValueType
'*< Vertical flipped (270)'
Global___ScreenOrientation: typing_extensions.TypeAlias = ScreenOrientation

@typing.final
class ScreenFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    ORIENTATION_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    orientation: Global___ScreenOrientation.ValueType

    def __init__(self, *, data: builtins.bytes=..., orientation: Global___ScreenOrientation.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data', b'data', 'orientation', b'orientation']) -> None:
        ...
Global___ScreenFrame: typing_extensions.TypeAlias = ScreenFrame

@typing.final
class StartScreenStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StartScreenStreamRequest: typing_extensions.TypeAlias = StartScreenStreamRequest

@typing.final
class StopScreenStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StopScreenStreamRequest: typing_extensions.TypeAlias = StopScreenStreamRequest

@typing.final
class SendInputEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    key: Global___InputKey.ValueType
    type: Global___InputType.ValueType

    def __init__(self, *, key: Global___InputKey.ValueType=..., type: Global___InputType.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key', 'type', b'type']) -> None:
        ...
Global___SendInputEventRequest: typing_extensions.TypeAlias = SendInputEventRequest

@typing.final
class StartVirtualDisplayRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FIRST_FRAME_FIELD_NUMBER: builtins.int
    SEND_INPUT_FIELD_NUMBER: builtins.int
    send_input: builtins.bool
    '*< Optional: send flipper input'

    @property
    def first_frame(self) -> Global___ScreenFrame:
        """*< Optional: screen frame to show"""

    def __init__(self, *, first_frame: Global___ScreenFrame | None=..., send_input: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['first_frame', b'first_frame']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['first_frame', b'first_frame', 'send_input', b'send_input']) -> None:
        ...
Global___StartVirtualDisplayRequest: typing_extensions.TypeAlias = StartVirtualDisplayRequest

@typing.final
class StopVirtualDisplayRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StopVirtualDisplayRequest: typing_extensions.TypeAlias = StopVirtualDisplayRequest