"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _FileType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FileTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[File._FileType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FILE: File._FileType.ValueType
        'default value'
        DIR: File._FileType.ValueType

    class FileType(_FileType, metaclass=_FileTypeEnumTypeWrapper):
        ...
    FILE: File.FileType.ValueType
    'default value'
    DIR: File.FileType.ValueType
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    MD5SUM_FIELD_NUMBER: builtins.int
    type: Global___File.FileType.ValueType
    name: builtins.str
    size: builtins.int
    data: builtins.bytes
    md5sum: builtins.str

    def __init__(self, *, type: Global___File.FileType.ValueType=..., name: builtins.str=..., size: builtins.int=..., data: builtins.bytes=..., md5sum: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['data', b'data', 'md5sum', b'md5sum', 'name', b'name', 'size', b'size', 'type', b'type']) -> None:
        ...
Global___File: typing_extensions.TypeAlias = File

@typing.final
class InfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___InfoRequest: typing_extensions.TypeAlias = InfoRequest

@typing.final
class InfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOTAL_SPACE_FIELD_NUMBER: builtins.int
    FREE_SPACE_FIELD_NUMBER: builtins.int
    total_space: builtins.int
    free_space: builtins.int

    def __init__(self, *, total_space: builtins.int=..., free_space: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['free_space', b'free_space', 'total_space', b'total_space']) -> None:
        ...
Global___InfoResponse: typing_extensions.TypeAlias = InfoResponse

@typing.final
class TimestampRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___TimestampRequest: typing_extensions.TypeAlias = TimestampRequest

@typing.final
class TimestampResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESTAMP_FIELD_NUMBER: builtins.int
    timestamp: builtins.int

    def __init__(self, *, timestamp: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['timestamp', b'timestamp']) -> None:
        ...
Global___TimestampResponse: typing_extensions.TypeAlias = TimestampResponse

@typing.final
class StatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___StatRequest: typing_extensions.TypeAlias = StatRequest

@typing.final
class StatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: builtins.int

    @property
    def file(self) -> Global___File:
        ...

    def __init__(self, *, file: Global___File | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['file', b'file']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['file', b'file']) -> None:
        ...
Global___StatResponse: typing_extensions.TypeAlias = StatResponse

@typing.final
class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    INCLUDE_MD5_FIELD_NUMBER: builtins.int
    FILTER_MAX_SIZE_FIELD_NUMBER: builtins.int
    path: builtins.str
    include_md5: builtins.bool
    filter_max_size: builtins.int

    def __init__(self, *, path: builtins.str=..., include_md5: builtins.bool=..., filter_max_size: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['filter_max_size', b'filter_max_size', 'include_md5', b'include_md5', 'path', b'path']) -> None:
        ...
Global___ListRequest: typing_extensions.TypeAlias = ListRequest

@typing.final
class ListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: builtins.int

    @property
    def file(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___File]:
        ...

    def __init__(self, *, file: collections.abc.Iterable[Global___File] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['file', b'file']) -> None:
        ...
Global___ListResponse: typing_extensions.TypeAlias = ListResponse

@typing.final
class ReadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___ReadRequest: typing_extensions.TypeAlias = ReadRequest

@typing.final
class ReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILE_FIELD_NUMBER: builtins.int

    @property
    def file(self) -> Global___File:
        ...

    def __init__(self, *, file: Global___File | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['file', b'file']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['file', b'file']) -> None:
        ...
Global___ReadResponse: typing_extensions.TypeAlias = ReadResponse

@typing.final
class WriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    FILE_FIELD_NUMBER: builtins.int
    path: builtins.str

    @property
    def file(self) -> Global___File:
        ...

    def __init__(self, *, path: builtins.str=..., file: Global___File | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['file', b'file']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['file', b'file', 'path', b'path']) -> None:
        ...
Global___WriteRequest: typing_extensions.TypeAlias = WriteRequest

@typing.final
class DeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    RECURSIVE_FIELD_NUMBER: builtins.int
    path: builtins.str
    recursive: builtins.bool

    def __init__(self, *, path: builtins.str=..., recursive: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path', 'recursive', b'recursive']) -> None:
        ...
Global___DeleteRequest: typing_extensions.TypeAlias = DeleteRequest

@typing.final
class MkdirRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___MkdirRequest: typing_extensions.TypeAlias = MkdirRequest

@typing.final
class Md5sumRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str

    def __init__(self, *, path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['path', b'path']) -> None:
        ...
Global___Md5sumRequest: typing_extensions.TypeAlias = Md5sumRequest

@typing.final
class Md5sumResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MD5SUM_FIELD_NUMBER: builtins.int
    md5sum: builtins.str

    def __init__(self, *, md5sum: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['md5sum', b'md5sum']) -> None:
        ...
Global___Md5sumResponse: typing_extensions.TypeAlias = Md5sumResponse

@typing.final
class RenameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OLD_PATH_FIELD_NUMBER: builtins.int
    NEW_PATH_FIELD_NUMBER: builtins.int
    old_path: builtins.str
    new_path: builtins.str

    def __init__(self, *, old_path: builtins.str=..., new_path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['new_path', b'new_path', 'old_path', b'old_path']) -> None:
        ...
Global___RenameRequest: typing_extensions.TypeAlias = RenameRequest

@typing.final
class BackupCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARCHIVE_PATH_FIELD_NUMBER: builtins.int
    archive_path: builtins.str

    def __init__(self, *, archive_path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['archive_path', b'archive_path']) -> None:
        ...
Global___BackupCreateRequest: typing_extensions.TypeAlias = BackupCreateRequest

@typing.final
class BackupRestoreRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARCHIVE_PATH_FIELD_NUMBER: builtins.int
    archive_path: builtins.str

    def __init__(self, *, archive_path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['archive_path', b'archive_path']) -> None:
        ...
Global___BackupRestoreRequest: typing_extensions.TypeAlias = BackupRestoreRequest

@typing.final
class TarExtractRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TAR_PATH_FIELD_NUMBER: builtins.int
    OUT_PATH_FIELD_NUMBER: builtins.int
    tar_path: builtins.str
    out_path: builtins.str

    def __init__(self, *, tar_path: builtins.str=..., out_path: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['out_path', b'out_path', 'tar_path', b'tar_path']) -> None:
        ...
Global___TarExtractRequest: typing_extensions.TypeAlias = TarExtractRequest